"""
Regenerates docs/diqduq-api-docs.html: a single self-contained HTML page
documenting diqduq's public API (every name in `diqduq.__all__` -- see
diqduq/__init__.py), built with pdoc directly from that code's own
docstrings and type hints. Modeled directly on arsgrammatica's
docs/build_api_docs.py (diqduq's own copy lives in utilities/ rather than
docs/ -- see notes/USAGE.md's "Files" for why).

Deliberately scoped to ONE page for the top-level package only, not a
multi-page site with one page per submodule (models.py, rendering.py,
etc.) -- pdoc still pulls each name's real signature and docstring from
wherever it's actually defined, so nothing is lost by excluding submodule
pages; it just keeps the output to the same single browsable file
regardless of how many internal modules the package grows into. The
exclude list is computed from the package's own submodules (via
pkgutil.iter_modules) rather than hardcoded, so a new internal module added
later is excluded automatically without needing an edit here.

Run from anywhere:
    python utilities/build_api_docs.py

Requires pdoc (`pip install pdoc --break-system-packages`); not currently
pinned in a requirements file anywhere in this repo, so install it by hand
if it's missing.
"""

import pkgutil
import sys
import tempfile
from pathlib import Path

# This script lives in utilities/, one directory below the repo root.
# REPO_ROOT is that root either way (whether this script lives in utilities/
# or, before that move, docs/ -- both are one level down), so the `import
# diqduq` sys.path fix-up below is unaffected by the move. OUTPUT_FILE,
# unlike REPO_ROOT, is NOT derived from this script's own directory (that
# would follow the script if it moved again) -- it's pinned explicitly to
# docs/diqduq-api-docs.html, since the generated page's location is a
# published-docs decision, not a "wherever this script happens to live" one.
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = REPO_ROOT / "docs" / "diqduq-api-docs.html"

# So `import diqduq` below works no matter what directory this script is
# invoked from.
sys.path.insert(0, str(REPO_ROOT))

try:
    import pdoc
    import pdoc.render
except ImportError:
    sys.exit(
        "pdoc is required to build the API docs but isn't installed.\n"
        "Install it with: pip install pdoc --break-system-packages"
    )

import diqduq


def _submodule_exclude_patterns():
    """One '!diqduq.<name>' pattern per actual submodule of the diqduq
    package, so pdoc renders only the top-level package page (see this
    file's own docstring for why)."""
    return [
        f"!diqduq.{info.name}"
        for info in pkgutil.iter_modules(diqduq.__path__)
    ]


def build():
    pdoc.render.configure(
        docformat="google",
        footer_text=(
            "diqduq public API -- generated by utilities/build_api_docs.py "
            "from the package's own docstrings; do not edit by hand."
        ),
        search=False,
        math=False,
        mermaid=False,
    )

    with tempfile.TemporaryDirectory() as tmp:
        pdoc.pdoc(
            "diqduq",
            *_submodule_exclude_patterns(),
            output_directory=Path(tmp),
        )
        rendered = Path(tmp) / "diqduq.html"
        OUTPUT_FILE.write_bytes(rendered.read_bytes())

    print(f"Wrote {OUTPUT_FILE} ({OUTPUT_FILE.stat().st_size:,} bytes)")


if __name__ == "__main__":
    build()
